target("content_test")
    set_kind("binary")
    add_files("Content_test.cpp")
    add_deps("ant2d")
    add_packages("catch2") 
    after_build(function (target)
        os.cp("tests/assets/", path.join(target:targetdir(), "assets"), {rootdir = "tests/assets/"})
        print("copy test assets to target dir success\n")
    end)
target_end()

target("buffer_test")
    set_kind("binary")
    add_files("$(projectdir)/gfx/bk/buffer.cpp")
    add_files("Buffer_test.cpp")
    add_files("mocks/*.cpp")
    add_packages("catch2") 
target_end()

target("debug_test")
    set_kind("binary")
    add_files("$(projectdir)/third_party/fmt/src/format.cc")
    add_files("Debug_test.cpp")
target_end()

target("image_test")
    set_kind("binary")
    add_files("$(projectdir)/asset/image.cpp")
    add_files("$(projectdir)/asset/stb_image.cpp")
    add_files("$(projectdir)/utils/Content.cpp")
    add_files("$(projectdir)/third_party/fmt/src/format.cc")
    add_files("Image_test.cpp")
    add_packages("stb") 
    add_packages("catch2") 
target_end()

target("texture_test")
    set_kind("binary")
    add_files("Texture_test.cpp")
    add_files("$(projectdir)/gfx/bk/texture.cpp")
    add_files("mocks/*.cpp")
    add_files("$(projectdir)/asset/image.cpp")
    add_files("$(projectdir)/asset/stb_image.cpp")
    add_files("$(projectdir)/utils/Content.cpp")
    add_files("$(projectdir)/third_party/fmt/src/format.cc")
    add_packages("stb")
    add_packages("catch2") 
target_end()
